//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoveProxy.CarvajalCFDIServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.levicom.com.mx/", ConfigurationName="CarvajalCFDIServicio.CFDIServiceSoap")]
    public interface CFDIServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje LoginRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.levicom.com.mx/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CoveProxy.CarvajalCFDIServicio.LoginResponse Login(CoveProxy.CarvajalCFDIServicio.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje LogoutRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.levicom.com.mx/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CoveProxy.CarvajalCFDIServicio.LogoutResponse Logout(CoveProxy.CarvajalCFDIServicio.LogoutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje GetTimbreRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.levicom.com.mx/GetTimbre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CoveProxy.CarvajalCFDIServicio.GetTimbreResponse GetTimbre(CoveProxy.CarvajalCFDIServicio.GetTimbreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje CancelCFDIRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.levicom.com.mx/CancelCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CoveProxy.CarvajalCFDIServicio.CancelCFDIResponse CancelCFDI(CoveProxy.CarvajalCFDIServicio.CancelCFDIRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.levicom.com.mx/")]
    public partial class CFDIWebServiceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string authenticatedTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthenticatedToken {
            get {
                return this.authenticatedTokenField;
            }
            set {
                this.authenticatedTokenField = value;
                this.RaisePropertyChanged("AuthenticatedToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://www.levicom.com.mx/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.levicom.com.mx/")]
        public CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader;
        
        public LoginRequest() {
        }
        
        public LoginRequest(CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader) {
            this.CFDIWebServiceHeader = CFDIWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://www.levicom.com.mx/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.levicom.com.mx/", Order=0)]
        public System.Xml.XmlElement LoginResult;
        
        public LoginResponse() {
        }
        
        public LoginResponse(System.Xml.XmlElement LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://www.levicom.com.mx/", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.levicom.com.mx/")]
        public CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader) {
            this.CFDIWebServiceHeader = CFDIWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://www.levicom.com.mx/", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.levicom.com.mx/", Order=0)]
        public System.Xml.XmlElement LogoutResult;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(System.Xml.XmlElement LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTimbre", WrapperNamespace="http://www.levicom.com.mx/", IsWrapped=true)]
    public partial class GetTimbreRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.levicom.com.mx/")]
        public CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.levicom.com.mx/", Order=0)]
        public System.Xml.XmlElement cfdi;
        
        public GetTimbreRequest() {
        }
        
        public GetTimbreRequest(CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader, System.Xml.XmlElement cfdi) {
            this.CFDIWebServiceHeader = CFDIWebServiceHeader;
            this.cfdi = cfdi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTimbreResponse", WrapperNamespace="http://www.levicom.com.mx/", IsWrapped=true)]
    public partial class GetTimbreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.levicom.com.mx/", Order=0)]
        public System.Xml.XmlElement GetTimbreResult;
        
        public GetTimbreResponse() {
        }
        
        public GetTimbreResponse(System.Xml.XmlElement GetTimbreResult) {
            this.GetTimbreResult = GetTimbreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelCFDI", WrapperNamespace="http://www.levicom.com.mx/", IsWrapped=true)]
    public partial class CancelCFDIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.levicom.com.mx/")]
        public CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.levicom.com.mx/", Order=0)]
        public System.Xml.XmlElement cancellations;
        
        public CancelCFDIRequest() {
        }
        
        public CancelCFDIRequest(CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader, System.Xml.XmlElement cancellations) {
            this.CFDIWebServiceHeader = CFDIWebServiceHeader;
            this.cancellations = cancellations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelCFDIResponse", WrapperNamespace="http://www.levicom.com.mx/", IsWrapped=true)]
    public partial class CancelCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.levicom.com.mx/", Order=0)]
        public System.Xml.XmlElement CancelCFDIResult;
        
        public CancelCFDIResponse() {
        }
        
        public CancelCFDIResponse(System.Xml.XmlElement CancelCFDIResult) {
            this.CancelCFDIResult = CancelCFDIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CFDIServiceSoapChannel : CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFDIServiceSoapClient : System.ServiceModel.ClientBase<CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap>, CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap {
        
        public CFDIServiceSoapClient() {
        }
        
        public CFDIServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFDIServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFDIServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFDIServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoveProxy.CarvajalCFDIServicio.LoginResponse CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap.Login(CoveProxy.CarvajalCFDIServicio.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public System.Xml.XmlElement Login(CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader) {
            CoveProxy.CarvajalCFDIServicio.LoginRequest inValue = new CoveProxy.CarvajalCFDIServicio.LoginRequest();
            inValue.CFDIWebServiceHeader = CFDIWebServiceHeader;
            CoveProxy.CarvajalCFDIServicio.LoginResponse retVal = ((CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap)(this)).Login(inValue);
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoveProxy.CarvajalCFDIServicio.LogoutResponse CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap.Logout(CoveProxy.CarvajalCFDIServicio.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public System.Xml.XmlElement Logout(CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader) {
            CoveProxy.CarvajalCFDIServicio.LogoutRequest inValue = new CoveProxy.CarvajalCFDIServicio.LogoutRequest();
            inValue.CFDIWebServiceHeader = CFDIWebServiceHeader;
            CoveProxy.CarvajalCFDIServicio.LogoutResponse retVal = ((CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap)(this)).Logout(inValue);
            return retVal.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoveProxy.CarvajalCFDIServicio.GetTimbreResponse CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap.GetTimbre(CoveProxy.CarvajalCFDIServicio.GetTimbreRequest request) {
            return base.Channel.GetTimbre(request);
        }
        
        public System.Xml.XmlElement GetTimbre(CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader, System.Xml.XmlElement cfdi) {
            CoveProxy.CarvajalCFDIServicio.GetTimbreRequest inValue = new CoveProxy.CarvajalCFDIServicio.GetTimbreRequest();
            inValue.CFDIWebServiceHeader = CFDIWebServiceHeader;
            inValue.cfdi = cfdi;
            CoveProxy.CarvajalCFDIServicio.GetTimbreResponse retVal = ((CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap)(this)).GetTimbre(inValue);
            return retVal.GetTimbreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoveProxy.CarvajalCFDIServicio.CancelCFDIResponse CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap.CancelCFDI(CoveProxy.CarvajalCFDIServicio.CancelCFDIRequest request) {
            return base.Channel.CancelCFDI(request);
        }
        
        public System.Xml.XmlElement CancelCFDI(CoveProxy.CarvajalCFDIServicio.CFDIWebServiceHeader CFDIWebServiceHeader, System.Xml.XmlElement cancellations) {
            CoveProxy.CarvajalCFDIServicio.CancelCFDIRequest inValue = new CoveProxy.CarvajalCFDIServicio.CancelCFDIRequest();
            inValue.CFDIWebServiceHeader = CFDIWebServiceHeader;
            inValue.cancellations = cancellations;
            CoveProxy.CarvajalCFDIServicio.CancelCFDIResponse retVal = ((CoveProxy.CarvajalCFDIServicio.CFDIServiceSoap)(this)).CancelCFDI(inValue);
            return retVal.CancelCFDIResult;
        }
    }
}
