//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoveProxy.CoveRespuestaServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/service/", ConfigurationName="CoveRespuestaServicio.IReceptor")]
    public interface IReceptor {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConsultarRespuestaCove no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ConsultarRespuestaCove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CoveProxy.CoveRespuestaServicio.ConsultarRespuestaCoveResponse ConsultarRespuestaCove(CoveProxy.CoveRespuestaServicio.ConsultarRespuestaCoveRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class SolicitarConsultarRespuestaCoveServicio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroOperacionField;
        
        private FirmaElectronica firmaElectronicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
                this.RaisePropertyChanged("numeroOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FirmaElectronica firmaElectronica {
            get {
                return this.firmaElectronicaField;
            }
            set {
                this.firmaElectronicaField = value;
                this.RaisePropertyChanged("firmaElectronica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FirmaElectronica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] certificadoField;
        
        private string cadenaOriginalField;
        
        private byte[] firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
                this.RaisePropertyChanged("certificado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
                this.RaisePropertyChanged("cadenaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
                this.RaisePropertyChanged("firma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class RespuestaOperacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroFacturaORelacionFacturasField;
        
        private bool contieneErrorField;
        
        private string eDocumentField;
        
        private string[] erroresField;
        
        private string cadenaOriginalField;
        
        private string selloDigitalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroFacturaORelacionFacturas {
            get {
                return this.numeroFacturaORelacionFacturasField;
            }
            set {
                this.numeroFacturaORelacionFacturasField = value;
                this.RaisePropertyChanged("numeroFacturaORelacionFacturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool contieneError {
            get {
                return this.contieneErrorField;
            }
            set {
                this.contieneErrorField = value;
                this.RaisePropertyChanged("contieneError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string eDocument {
            get {
                return this.eDocumentField;
            }
            set {
                this.eDocumentField = value;
                this.RaisePropertyChanged("eDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje", IsNullable=false)]
        public string[] errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
                this.RaisePropertyChanged("errores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
                this.RaisePropertyChanged("cadenaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string selloDigital {
            get {
                return this.selloDigitalField;
            }
            set {
                this.selloDigitalField = value;
                this.RaisePropertyChanged("selloDigital");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class RespuestaPeticion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroOperacionField;
        
        private System.DateTime horaRecepcionField;
        
        private RespuestaOperacion[] respuestasOperacionesField;
        
        private string leyendaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
                this.RaisePropertyChanged("numeroOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime horaRecepcion {
            get {
                return this.horaRecepcionField;
            }
            set {
                this.horaRecepcionField = value;
                this.RaisePropertyChanged("horaRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuestasOperaciones", Order=2)]
        public RespuestaOperacion[] respuestasOperaciones {
            get {
                return this.respuestasOperacionesField;
            }
            set {
                this.respuestasOperacionesField = value;
                this.RaisePropertyChanged("respuestasOperaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
                this.RaisePropertyChanged("leyenda");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaCoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public CoveProxy.CoveRespuestaServicio.SolicitarConsultarRespuestaCoveServicio solicitarConsultarRespuestaCoveServicio;
        
        public ConsultarRespuestaCoveRequest() {
        }
        
        public ConsultarRespuestaCoveRequest(CoveProxy.CoveRespuestaServicio.SolicitarConsultarRespuestaCoveServicio solicitarConsultarRespuestaCoveServicio) {
            this.solicitarConsultarRespuestaCoveServicio = solicitarConsultarRespuestaCoveServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaCoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public CoveProxy.CoveRespuestaServicio.RespuestaPeticion solicitarConsultarRespuestaCoveServicioResponse;
        
        public ConsultarRespuestaCoveResponse() {
        }
        
        public ConsultarRespuestaCoveResponse(CoveProxy.CoveRespuestaServicio.RespuestaPeticion solicitarConsultarRespuestaCoveServicioResponse) {
            this.solicitarConsultarRespuestaCoveServicioResponse = solicitarConsultarRespuestaCoveServicioResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceptorChannel : CoveProxy.CoveRespuestaServicio.IReceptor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptorClient : System.ServiceModel.ClientBase<CoveProxy.CoveRespuestaServicio.IReceptor>, CoveProxy.CoveRespuestaServicio.IReceptor {
        
        public ReceptorClient() {
        }
        
        public ReceptorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoveProxy.CoveRespuestaServicio.ConsultarRespuestaCoveResponse CoveProxy.CoveRespuestaServicio.IReceptor.ConsultarRespuestaCove(CoveProxy.CoveRespuestaServicio.ConsultarRespuestaCoveRequest request) {
            return base.Channel.ConsultarRespuestaCove(request);
        }
        
        public CoveProxy.CoveRespuestaServicio.RespuestaPeticion ConsultarRespuestaCove(CoveProxy.CoveRespuestaServicio.SolicitarConsultarRespuestaCoveServicio solicitarConsultarRespuestaCoveServicio) {
            CoveProxy.CoveRespuestaServicio.ConsultarRespuestaCoveRequest inValue = new CoveProxy.CoveRespuestaServicio.ConsultarRespuestaCoveRequest();
            inValue.solicitarConsultarRespuestaCoveServicio = solicitarConsultarRespuestaCoveServicio;
            CoveProxy.CoveRespuestaServicio.ConsultarRespuestaCoveResponse retVal = ((CoveProxy.CoveRespuestaServicio.IReceptor)(this)).ConsultarRespuestaCove(inValue);
            return retVal.solicitarConsultarRespuestaCoveServicioResponse;
        }
    }
}
