//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoveProxy.CoveServicioVentanilla8 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/service/", ConfigurationName="CoveServicioVentanilla8.IReceptor")]
    public interface IReceptor {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación RecibirCove no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RecibirCove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComprobanteValorElectronicoBase))]
        CoveProxy.CoveServicioVentanilla8.RecibirCoveResponse RecibirCove(CoveProxy.CoveServicioVentanilla8.RecibirCoveRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación RecibirRelacionFacturasIA no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasIA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComprobanteValorElectronicoBase))]
        CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasIAResponse RecibirRelacionFacturasIA(CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasIARequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación RecibirRelacionFacturasNoIA no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasNoIA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComprobanteValorElectronicoBase))]
        CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasNoIAResponse RecibirRelacionFacturasNoIA(CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasNoIARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronico : ComprobanteValorElectronicoBase {
        
        private string numeroFacturaOriginalField;
        
        private FacturaCove facturaField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroFacturaOriginal {
            get {
                return this.numeroFacturaOriginalField;
            }
            set {
                this.numeroFacturaOriginalField = value;
                this.RaisePropertyChanged("numeroFacturaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FacturaCove factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
                this.RaisePropertyChanged("factura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Emisor emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
                this.RaisePropertyChanged("emisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Destinatario destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
                this.RaisePropertyChanged("destinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias", Order=4)]
        public Mercancia[] mercancias {
            get {
                return this.mercanciasField;
            }
            set {
                this.mercanciasField = value;
                this.RaisePropertyChanged("mercancias");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacturaNoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacturaIA))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaCove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int certificadoOrigenField;
        
        private string numeroExportadorAutorizadoField;
        
        private int subdivisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int certificadoOrigen {
            get {
                return this.certificadoOrigenField;
            }
            set {
                this.certificadoOrigenField = value;
                this.RaisePropertyChanged("certificadoOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string numeroExportadorAutorizado {
            get {
                return this.numeroExportadorAutorizadoField;
            }
            set {
                this.numeroExportadorAutorizadoField = value;
                this.RaisePropertyChanged("numeroExportadorAutorizado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int subdivision {
            get {
                return this.subdivisionField;
            }
            set {
                this.subdivisionField = value;
                this.RaisePropertyChanged("subdivision");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Acuse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroDeOperacionField;
        
        private System.DateTime horaRecepcionField;
        
        private string mensajeInformativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroDeOperacion {
            get {
                return this.numeroDeOperacionField;
            }
            set {
                this.numeroDeOperacionField = value;
                this.RaisePropertyChanged("numeroDeOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime horaRecepcion {
            get {
                return this.horaRecepcionField;
            }
            set {
                this.horaRecepcionField = value;
                this.RaisePropertyChanged("horaRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensajeInformativo {
            get {
                return this.mensajeInformativoField;
            }
            set {
                this.mensajeInformativoField = value;
                this.RaisePropertyChanged("mensajeInformativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Domicilio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string calleField;
        
        private string numeroExteriorField;
        
        private string numeroInteriorField;
        
        private string coloniaField;
        
        private string localidadField;
        
        private string municipioField;
        
        private string entidadFederativaField;
        
        private string paisField;
        
        private string codigoPostalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
                this.RaisePropertyChanged("calle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string numeroExterior {
            get {
                return this.numeroExteriorField;
            }
            set {
                this.numeroExteriorField = value;
                this.RaisePropertyChanged("numeroExterior");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string numeroInterior {
            get {
                return this.numeroInteriorField;
            }
            set {
                this.numeroInteriorField = value;
                this.RaisePropertyChanged("numeroInterior");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
                this.RaisePropertyChanged("colonia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
                this.RaisePropertyChanged("municipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string entidadFederativa {
            get {
                return this.entidadFederativaField;
            }
            set {
                this.entidadFederativaField = value;
                this.RaisePropertyChanged("entidadFederativa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
                this.RaisePropertyChanged("codigoPostal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Emisor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Destinatario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public abstract partial class Persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tipoIdentificadorField;
        
        private string identificacionField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string nombreField;
        
        private Domicilio domicilioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int tipoIdentificador {
            get {
                return this.tipoIdentificadorField;
            }
            set {
                this.tipoIdentificadorField = value;
                this.RaisePropertyChanged("tipoIdentificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
                this.RaisePropertyChanged("identificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Domicilio domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
                this.RaisePropertyChanged("domicilio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Emisor : Persona {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Destinatario : Persona {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class DescripcionMercancia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string marcaField;
        
        private string modeloField;
        
        private string subModeloField;
        
        private string numeroSerieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subModelo {
            get {
                return this.subModeloField;
            }
            set {
                this.subModeloField = value;
                this.RaisePropertyChanged("subModelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
                this.RaisePropertyChanged("numeroSerie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Mercancia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionGenericaField;
        
        private string claveUnidadMedidaField;
        
        private string tipoMonedaField;
        
        private decimal cantidadField;
        
        private decimal valorUnitarioField;
        
        private decimal valorTotalField;
        
        private decimal valorDolaresField;
        
        private DescripcionMercancia[] descripcionesEspecificasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descripcionGenerica {
            get {
                return this.descripcionGenericaField;
            }
            set {
                this.descripcionGenericaField = value;
                this.RaisePropertyChanged("descripcionGenerica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string claveUnidadMedida {
            get {
                return this.claveUnidadMedidaField;
            }
            set {
                this.claveUnidadMedidaField = value;
                this.RaisePropertyChanged("claveUnidadMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal valorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
                this.RaisePropertyChanged("valorUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
                this.RaisePropertyChanged("valorTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal valorDolares {
            get {
                return this.valorDolaresField;
            }
            set {
                this.valorDolaresField = value;
                this.RaisePropertyChanged("valorDolares");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descripcionesEspecificas", Order=7)]
        public DescripcionMercancia[] descripcionesEspecificas {
            get {
                return this.descripcionesEspecificasField;
            }
            set {
                this.descripcionesEspecificasField = value;
                this.RaisePropertyChanged("descripcionesEspecificas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FirmaElectronica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] certificadoField;
        
        private string cadenaOriginalField;
        
        private byte[] firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
                this.RaisePropertyChanged("certificado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
                this.RaisePropertyChanged("cadenaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
                this.RaisePropertyChanged("firma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronicoNoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronicoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronico))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public abstract partial class ComprobanteValorElectronicoBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string edocumentField;
        
        private TipoOperacion tipoOperacionField;
        
        private string[] patenteAduanalField;
        
        private System.DateTime fechaExpedicionField;
        
        private string observacionesField;
        
        private string[] rfcConsultaField;
        
        private int tipoFiguraField;
        
        private string correoElectronicoField;
        
        private FirmaElectronica firmaElectronicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("e-document", IsNullable=true, Order=0)]
        public string edocument {
            get {
                return this.edocumentField;
            }
            set {
                this.edocumentField = value;
                this.RaisePropertyChanged("edocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoOperacion tipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
                this.RaisePropertyChanged("tipoOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patenteAduanal", Order=2)]
        public string[] patenteAduanal {
            get {
                return this.patenteAduanalField;
            }
            set {
                this.patenteAduanalField = value;
                this.RaisePropertyChanged("patenteAduanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime fechaExpedicion {
            get {
                return this.fechaExpedicionField;
            }
            set {
                this.fechaExpedicionField = value;
                this.RaisePropertyChanged("fechaExpedicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rfcConsulta", Order=5)]
        public string[] rfcConsulta {
            get {
                return this.rfcConsultaField;
            }
            set {
                this.rfcConsultaField = value;
                this.RaisePropertyChanged("rfcConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int tipoFigura {
            get {
                return this.tipoFiguraField;
            }
            set {
                this.tipoFiguraField = value;
                this.RaisePropertyChanged("tipoFigura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public FirmaElectronica firmaElectronica {
            get {
                return this.firmaElectronicaField;
            }
            set {
                this.firmaElectronicaField = value;
                this.RaisePropertyChanged("firmaElectronica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public enum TipoOperacion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TOCE.IMP")]
        TOCEIMP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TOCE.EXP")]
        TOCEEXP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronicoNoIA : ComprobanteValorElectronicoBase {
        
        private string numeroRelacionFacturasField;
        
        private FacturaNoIA[] facturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroRelacionFacturas {
            get {
                return this.numeroRelacionFacturasField;
            }
            set {
                this.numeroRelacionFacturasField = value;
                this.RaisePropertyChanged("numeroRelacionFacturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facturas", Order=1)]
        public FacturaNoIA[] facturas {
            get {
                return this.facturasField;
            }
            set {
                this.facturasField = value;
                this.RaisePropertyChanged("facturas");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaNoIA : FacturaCove {
        
        private string numeroFacturaField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
                this.RaisePropertyChanged("numeroFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Emisor emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
                this.RaisePropertyChanged("emisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Destinatario destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
                this.RaisePropertyChanged("destinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias", Order=3)]
        public Mercancia[] mercancias {
            get {
                return this.mercanciasField;
            }
            set {
                this.mercanciasField = value;
                this.RaisePropertyChanged("mercancias");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronicoIA : ComprobanteValorElectronicoBase {
        
        private string numeroRelacionFacturasField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private FacturaIA[] facturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroRelacionFacturas {
            get {
                return this.numeroRelacionFacturasField;
            }
            set {
                this.numeroRelacionFacturasField = value;
                this.RaisePropertyChanged("numeroRelacionFacturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Emisor emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
                this.RaisePropertyChanged("emisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Destinatario destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
                this.RaisePropertyChanged("destinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facturas", Order=3)]
        public FacturaIA[] facturas {
            get {
                return this.facturasField;
            }
            set {
                this.facturasField = value;
                this.RaisePropertyChanged("facturas");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaIA : FacturaCove {
        
        private string numeroFacturaField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
                this.RaisePropertyChanged("numeroFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias", Order=1)]
        public Mercancia[] mercancias {
            get {
                return this.mercanciasField;
            }
            set {
                this.mercanciasField = value;
                this.RaisePropertyChanged("mercancias");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirCoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)]
        public CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronico[] solicitarRecibirCoveServicio;
        
        public RecibirCoveRequest() {
        }
        
        public RecibirCoveRequest(CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronico[] solicitarRecibirCoveServicio) {
            this.solicitarRecibirCoveServicio = solicitarRecibirCoveServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirCoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public CoveProxy.CoveServicioVentanilla8.Acuse solicitarRecibirCoveServicioResponse;
        
        public RecibirCoveResponse() {
        }
        
        public RecibirCoveResponse(CoveProxy.CoveServicioVentanilla8.Acuse solicitarRecibirCoveServicioResponse) {
            this.solicitarRecibirCoveServicioResponse = solicitarRecibirCoveServicioResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirRelacionFacturasIARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)]
        public CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio;
        
        public RecibirRelacionFacturasIARequest() {
        }
        
        public RecibirRelacionFacturasIARequest(CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio) {
            this.solicitarRecibirRelacionFacturasIAServicio = solicitarRecibirRelacionFacturasIAServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirRelacionFacturasIAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public CoveProxy.CoveServicioVentanilla8.Acuse solicitarRecibirRelacionFacturasIAServicioResponse;
        
        public RecibirRelacionFacturasIAResponse() {
        }
        
        public RecibirRelacionFacturasIAResponse(CoveProxy.CoveServicioVentanilla8.Acuse solicitarRecibirRelacionFacturasIAServicioResponse) {
            this.solicitarRecibirRelacionFacturasIAServicioResponse = solicitarRecibirRelacionFacturasIAServicioResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirRelacionFacturasNoIARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)]
        public CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio;
        
        public RecibirRelacionFacturasNoIARequest() {
        }
        
        public RecibirRelacionFacturasNoIARequest(CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio) {
            this.solicitarRecibirRelacionFacturasNoIAServicio = solicitarRecibirRelacionFacturasNoIAServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirRelacionFacturasNoIAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public CoveProxy.CoveServicioVentanilla8.Acuse solicitarRecibirRelacionFacturasNoIAServicioResponse;
        
        public RecibirRelacionFacturasNoIAResponse() {
        }
        
        public RecibirRelacionFacturasNoIAResponse(CoveProxy.CoveServicioVentanilla8.Acuse solicitarRecibirRelacionFacturasNoIAServicioResponse) {
            this.solicitarRecibirRelacionFacturasNoIAServicioResponse = solicitarRecibirRelacionFacturasNoIAServicioResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceptorChannel : CoveProxy.CoveServicioVentanilla8.IReceptor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptorClient : System.ServiceModel.ClientBase<CoveProxy.CoveServicioVentanilla8.IReceptor>, CoveProxy.CoveServicioVentanilla8.IReceptor {
        
        public ReceptorClient() {
        }
        
        public ReceptorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoveProxy.CoveServicioVentanilla8.RecibirCoveResponse CoveProxy.CoveServicioVentanilla8.IReceptor.RecibirCove(CoveProxy.CoveServicioVentanilla8.RecibirCoveRequest request) {
            return base.Channel.RecibirCove(request);
        }
        
        public CoveProxy.CoveServicioVentanilla8.Acuse RecibirCove(CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronico[] solicitarRecibirCoveServicio) {
            CoveProxy.CoveServicioVentanilla8.RecibirCoveRequest inValue = new CoveProxy.CoveServicioVentanilla8.RecibirCoveRequest();
            inValue.solicitarRecibirCoveServicio = solicitarRecibirCoveServicio;
            CoveProxy.CoveServicioVentanilla8.RecibirCoveResponse retVal = ((CoveProxy.CoveServicioVentanilla8.IReceptor)(this)).RecibirCove(inValue);
            return retVal.solicitarRecibirCoveServicioResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasIAResponse CoveProxy.CoveServicioVentanilla8.IReceptor.RecibirRelacionFacturasIA(CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasIARequest request) {
            return base.Channel.RecibirRelacionFacturasIA(request);
        }
        
        public CoveProxy.CoveServicioVentanilla8.Acuse RecibirRelacionFacturasIA(CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio) {
            CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasIARequest inValue = new CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasIARequest();
            inValue.solicitarRecibirRelacionFacturasIAServicio = solicitarRecibirRelacionFacturasIAServicio;
            CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasIAResponse retVal = ((CoveProxy.CoveServicioVentanilla8.IReceptor)(this)).RecibirRelacionFacturasIA(inValue);
            return retVal.solicitarRecibirRelacionFacturasIAServicioResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasNoIAResponse CoveProxy.CoveServicioVentanilla8.IReceptor.RecibirRelacionFacturasNoIA(CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasNoIARequest request) {
            return base.Channel.RecibirRelacionFacturasNoIA(request);
        }
        
        public CoveProxy.CoveServicioVentanilla8.Acuse RecibirRelacionFacturasNoIA(CoveProxy.CoveServicioVentanilla8.ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio) {
            CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasNoIARequest inValue = new CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasNoIARequest();
            inValue.solicitarRecibirRelacionFacturasNoIAServicio = solicitarRecibirRelacionFacturasNoIAServicio;
            CoveProxy.CoveServicioVentanilla8.RecibirRelacionFacturasNoIAResponse retVal = ((CoveProxy.CoveServicioVentanilla8.IReceptor)(this)).RecibirRelacionFacturasNoIA(inValue);
            return retVal.solicitarRecibirRelacionFacturasNoIAServicioResponse;
        }
    }
}
